# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FASTFOOD.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from FASTFOODPRINCIPAL import Ui_menu

class Ui_home(object):

    def __init__(self):
        self.id = ["dani","sib","toni","alex"]
        self.password = ["1234","5678","1234","5678"]

    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(1690, 752)
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 90, 881, 81))
        self.label_2.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 470, 101, 21))
        self.label_3.setStyleSheet("font: italic 14pt \"Baskerville\";\n"
"background-color: rgb(0, 255, 204);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 550, 121, 21))
        self.label_4.setStyleSheet("font: italic 14pt \"Baskerville\";\n"
"background-color: rgb(0, 255, 204);")
        self.label_4.setObjectName("label_4")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(205, 470, 171, 21))
        self.T1.setObjectName("T1")
        self.T2 = QtWidgets.QLineEdit(self.centralwidget)
        self.T2.setGeometry(QtCore.QRect(205, 550, 171, 21))
        self.T2.setObjectName("T2")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(180, 620, 113, 32))
        self.B1.setStyleSheet("")
        self.B1.setObjectName("B1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, -20, 1690, 752))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 441, 711))
        self.label_6.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -5, 431, 721))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 1691, 41))
        self.label_7.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 670, 1641, 51))
        self.label_8.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1640, 10, 51, 701))
        self.label_9.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 51, 721))
        self.label_10.setStyleSheet("background-color: rgb(0, 255, 204);\n"
"font: 24pt \"Bodoni 72\";\n"
"color: rgb(1, 1, 1);\n"
"")
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 60, 331, 371))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 420, 341, 241))
        self.label_12.setStyleSheet("\n"
"background-color: rgb(8, 102, 179);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(440, 60, 911, 141))
        self.label_13.setStyleSheet("\n"
"background-color: rgb(8, 102, 179);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(60, 50, 21, 381))
        self.label_14.setStyleSheet("\n"
"background-color: rgb(8, 102, 179);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(380, 60, 21, 361))
        self.label_15.setStyleSheet("\n"
"background-color: rgb(8, 102, 179);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(60, 50, 341, 16))
        self.label_16.setStyleSheet("\n"
"background-color: rgb(8, 102, 179);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_5.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.T2.raise_()
        self.T1.raise_()
        self.B1.raise_()
        self.label_13.raise_()
        self.label_2.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1690, 21))
        self.menubar.setObjectName("menubar")
        home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home)
        self.statusbar.setObjectName("statusbar")
        home.setStatusBar(self.statusbar)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "HOMEPAGE"))
        self.label_2.setText(_translate("home", "GESTIÓN FASTFOOD PIZZAS"))
        self.label_3.setText(_translate("home", "EMPLEADO"))
        self.label_4.setText(_translate("home", "CONTRASEÑA"))
        self.B1.setText(_translate("home", "ACCEDER"))
        self.B1.clicked.connect(self.go)
        self.B1.clicked.connect(home.close)
        self.label_5.setText(_translate("home", "<html><head/><body><p><img src=\":/newPrefix/Captura de Pantalla 2023-05-13 a las 3.51.47.png\"/></p></body></html>"))
        self.label.setText(_translate("home", "<html><head/><body><p><img src=\":/newPrefix/Captura de Pantalla 2023-05-13 a las 3.51.47.png\"/></p></body></html>"))
        self.label_11.setText(_translate("home", "<html><head/><body><p><img src=\":/newPrefix/Captura de Pantalla 2023-05-13 a las 15.48.15.png\"/></p></body></html>"))

    def go(self):
        self.n1 = self.T1.text()
        self.n2 = self.T2.text()
        for i in range (0,4):
            if(self.n1 == self.id[i] and self.n2 == self.password[i]):
                self.file = QtWidgets.QMainWindow()
                self.ui = Ui_menu()
                self.ui.setupUi(self.file)
                self.file.show()
import fotos_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(home)
    home.show()
    sys.exit(app.exec_())
